FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY pyproject.toml README.md ./
COPY libs ./libs
COPY services ./services
COPY alembic.ini ./
COPY alembic ./alembic
COPY tests ./tests
COPY infra ./infra

RUN pip install --no-cache-dir ".[dev]"
